version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: event-booking-api
    container_name: event-booking-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 8003:8000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=event_booking_api
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:8.0
    container_name: event-booking-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: event_booking_api
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 33067:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: event-booking-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8080:80

volumes:
  dbdata:
